controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      wheel_separation: 0.35  # 2 * 0.175 from your URDF
      wheel_radius: 0.035     # From your wheel dimensions
      odom_frame_id: odom
      base_frame_id: base_footprint
      open_loop: true
      enable_odom_tf: true
      cmd_vel_timeout: 0.5
      publish_limited_velocity: true
      use_stamped_vel: false

      
# controller_manager:
#   ros__parameters:
#     controller_list:
#       - type: "diff_drive_controller/DiffDriveController"
#         name: "diff_drive_controller"
#         left_wheel: "left_wheel_joint"
#         right_wheel: "right_wheel_joint"
#         cmd_vel_timeout: 0.5
#         wheel_separation: 0.5
#         wheel_radius: 0.1


