controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2
      max_linear_vel: 0.3
      min_linear_vel: 0.05
      lookahead_dist: 0.4
      use_odom: true
      odom_topic: "/odom"
      cmd_vel_topic: "/cmd_vel"
      wheel_separation: 0.5
      wheel_radius: 0.1
      base_frame_id: "base_footprint"

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

# behavior_server:
#   ros__parameters:
#     behavior_plugins: ["NavigateToPose", "AssistedTeleop", "BackUp"]

behavior_server:
  ros__parameters:
    plugins: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_behaviors/NavigateToPose"

bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"

recoveries_server:
  ros__parameters:
    costmap_topic: "global_costmap/costmap_raw"
    footprint_topic: "global_costmap/published_footprint"

global_costmap:
  global_costmap:
    ros__parameters:
      robot_base_frame: "base_footprint"
      update_frequency: 1.0

local_costmap:
  local_costmap:
    ros__parameters:
      robot_base_frame: "base_footprint"
      update_frequency: 5.0

amcl:
  ros__parameters:
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    # Laser parameters (crucial for real robot)
    laser_model_type: "likelihood_field"
    laser_min_range: 0.1
    laser_max_range: 12.0
    laser_max_beams: 60

map_server:
  ros__parameters:
    yaml_filename: /home/satish/capstone/capstone/src/capstone_ignition/maps/my_mappy.yaml
